log-level: "debug"

discovery-relays:
  - "wss://domain1.tld"
  - "wss://domian2.tld"

plugin-down: "/usr/local/bin/strfry-down-plugin"
plugin-config: "/var/local/strfry/down-plugin.json"
router-timeout: "600"
router-config: "/var/local/strfry/router.config"
sync-config: "/var/local/strfry/sync.json"
sync-strfry: "/usr/local/bin/strfry"
sync-strfry-config: "/etc/strfry/strfry.conf"
sync-strfry-log: "/var/local/strfry/logs/sync"
sync-status-file: "/var/local/strfry/sync-status.json"

users:
  - name: "alice"
    pubkey: "<32-byte-public-key-hex>"
    depth: 1
    relay-depth: 1
    dir: down
