log-level: "debug"

discovery-relays:
  - "wss://domain1.tld"
  - "wss://domian2.tld"

plugin-down: "/usr/bin/local/strfry-router-plugin"
plugin-config: "/var/local/strfry/router-plugin"
router-config: "/var/local/strfry/router.config"
sync-config: "/var/local/strfry/sync.json"
sync-strfry: "/var/bin/local/strfry"

users:
  - name: "alice"
    pubkey: "<32-byte-public-key-hex>"
    depth: 1
    relay-depth: 1
    dir: down
