log-level: "debug"

discovery-relays:
  - "wss://domain1.tld"
  - "wss://domian2.tld"

router-plugin-down: "/usr/bin/local/strfry-router-plugin"
router-plugin-config: "/var/local/strfry/router-plugin"
router-config: "/var/local/strfry/router.config"
sync-config: "/var/local/strfry/sync.json"
sync-strfry: "/usr/bin/local/strfry"
sync-strfry-config: "/etc/strfry/strfry.conf"
sync-status-file: "/var/local/strfry/sync-status.json"

users:
  - name: "alice"
    pubkey: "<32-byte-public-key-hex>"
    depth: 1
    relay-depth: 1
    dir: down
