log-level: "debug"

discovery-relays:
  - "wss://domain1.tld"
  - "wss://domian2.tld"

router-plugin-down-bin: "/usr/bin/local/strfry-router-plugin"
router-plugin-down-config: "/var/local/strfry/router-plugin.json"
router-config-base: "/var/local/strfry/router"
routers-config: "/var/local/strfry/routers.json"

sync-config: "/var/local/strfry/sync.json"
sync-status-file: "/var/local/strfry/sync-status.json"
sync-strfry-log-base: "/var/local/strfry/logs/sync"

strfry-bin: "/usr/bin/local/strfry"
strfry-config: "/etc/strfry/strfry.conf"

users:
  - name: "alice"
    pubkey: "<32-byte-public-key-hex>"
    depth: 1
    relay-depth: 1
    dir: down
